### PR TITLE
Add additional CI targets

### LINKED ISSUE #1: Add CI targets
Tests should run on 0.12 as well as on iojs.

### PR DESCRIPTION
**Pull request by jo**
Add targets for
- 0.12
- 0.11
- iojs
  And fix badges.

Closes #1

### CODE REVIEW

**Comment by jo** [comment]
Hi @pateketrueke
I don't know why the tests are failing even for 0.10. The tests also fail locally on iojs.
I tried to get the tests running in order to write a proper test for #3.

**Comment by pateketrueke** [comment]
I know exactly what happened, sorry for that.

Please rebase from the develop branch again.

Thanks for your feedback!

**Comment by pateketrueke** [comment]
Travis-CI is OK now. :beers:

https://travis-ci.org/pateketrueke/deref/builds/68329139

**Comment by jo** [comment]
Thanks!

**Pull request closed without merging**
